version: "3.7"
services:
  pgvector:
    image: pgvector/pgvector:pg16
    platform: linux/x86_64
    environment:
      POSTGRES_DB: "vigelon_rag"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"
    volumes:
      - pgvector-db:/var/lib/postgresql/data
volumes:
  pgvector-db: